GNU Stow
========
Adam Spiers <stow@adamspiers.org>
v2.3.0, March 19, 2017

This is GNU Stow, a symlink farm manager program which takes distinct
packages of software and/or data located in separate directories on
the filesystem, and makes them appear to be installed in the same
place.  For example, `/usr/local/bin` could contain symlinks to files
within `/usr/local/stow/emacs/bin`, `/usr/local/stow/perl/bin` etc., and
likewise recursively for any other subdirectories such as `.../share`,
`.../man`, and so on.

This is particularly useful for keeping track of system-wide and
per-user installations of software built from source, but can also
facilitate a more controlled approach to management of configuration
files in the user's home directory, especially when coupled with
version control systems.

Stow is implemented as a combination of a Perl script providing a CLI
interface, and a backend Perl module which does most of the work.

You can get the latest information about Stow from the home page:

    http://www.gnu.org/software/stow/

License
-------

Stow is free software, licensed under the GNU General Public License,
which can be found in the file link:LICENSE[LICENSE].

Brief history
-------------

Stow was inspired by Carnegie Mellon's "Depot" program, but is
substantially simpler.  Whereas Depot requires database files to keep
things in sync, Stow stores no extra state between runs, so there's no
danger (as there is in Depot) of mangling directories when file
hierarchies don't match the database.  Also unlike Depot, Stow will
never delete any files, directories, or links that appear in a Stow
directory (e.g., `/usr/local/stow/emacs`), so it's always possible to
rebuild the target tree (e.g., `/usr/local`).
